Brew no longer uses casks
```
jeffwidman@Jeffs-14-MBP-M3 ~ % /opt/homebrew/bin/brew tap 'homebrew/cask'
Error: Tapping homebrew/cask is no longer typically necessary.
Add --force if you are sure you need it for contributing to Homebrew.
```