Remove `fasd` due to upstream repo archival
```
jeffwidman@Jeffs-14-MBP-M3 ~ % /opt/homebrew/bin/brew install 'fasd'
Error: fasd has been disabled because it has an archived upstream repository!
```

A little digging shows the replacement story is complicated... https://www.reddit.com/r/commandline/comments/z7n7hb/replacement_for_fasd/

For me `zsh-autosuggestions` has been working well enough lately.