Update `virtualenvwrapper` instructions
Trying a global `pip3 install virtualenvwrapper` resulted in the
following message:

```shell
~/C/o/flask-debugtoolbar ❯❯❯ syspip3 install virtualenvwrapper
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

I explored using `brew install virtualenvwrapper`, but ran into an issue
that `prezto` wouldn't recognize `virtualenvwrapper` w/o manually
sourcing it. So it's simpler to stick with installing virtualenvwrapper
globally into site packages.

Also removed an old note about `virtualenv` package now that it's
included by default with all modern pythons.